server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        format-sql: true
        dialect : org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      
file:
  upload:
    location: C:\fitness   
     
steps.coin: 1000
rupees.coin: 10
              
      
      
#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:8080/oauth/check_token
#      user-info-uri: http://localhost:8081/v1/utilities   
#    client:
#      client-id:  User
#      client-secret: 12345
      
         
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace

#server.port = 8083
#spring.application.name=employee-info-service
#
#spring.datasource.url=jdbc:mysql://localhost:3306/employee?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.show-sql=true
#
#
## The SQL dialect makes Hibernate generate better SQL for the chosen database
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#
## Hibernate ddl auto (create, create-drop, validate, update)
#spring.jpa.hibernate.ddl-auto = update
#
##logging
#logging.level.com.te.springboot=INFO
#logging.pattern.file= %d [%thread] %cyan(%logger{15}) - %msg %n
#logging.file.name=LogFile/mylog.log
        